version: '3'
services:
  frontend:
    build: ./frontend/supermercado-frontend-react
    ports:
      - "3000:80"
    depends_on:
      - inventario
      - auth
      - carrito
    container_name: frontend

  inventario:
    build: ./backend/supermercado-inventario
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/supermarket
    depends_on:
      - mongo
    container_name: inventario

  auth:
    build: ./backend/supermercado-auth
    ports:
      - "4000:4000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=auth_db
    depends_on:
      - mysql
    container_name: auth

  carrito:
    build: ./backend/supermercado-carrito
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/supermarket
    depends_on:
      - mongo
    container_name: carrito

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongodb

volumes:
  mongo-data:
  mysql-data:
